### ISSUE TITLE
Extension

### ISSUE THREAD

**Issue by Vorvald** [eslachance/dithcord#1]
Hi, I'm working on implementing a discord client for an unrelated project. Since my work is in early stages and similar in scope to this library I'd like to contribute if it is intended to be usable in production.
Specifically I'd like to implement secondary features (https://discordapp.com/developers/docs/topics/gateway#tracking-state for instance) while the nitty-gritty wss/event handling parts are in flux.

Is there a preferred way of getting in touch with the current devs to discuss these kind of things?

**Comment by eslachance** [comment]
Hi Vorvald! 

I think we're... quite a few people actually somewhat working on a Clojure lib for Discord. I've heard of at least 3 others, in various stages of development. I, myself, have had... unfortunately little success in getting beyond WSS simply because of my inexperience with Clojure. I've put this on hold just a little bit until I feel a little more comfortable (I'll admit, I'm doing some interesting things on the Discord.js side at the moment). 

Now, of course I'd love it if I could work on Dithcord with others - or maybe we could all get together and actually work as a team, who knows maybe we could come up with some better plan and more motivation... 

You can get in touch with me on Discord (of course), I'm LuckyEvie#4611 , you can find me on most dev servers - Discord Developers, Discord API, The Coding Den, Canary Testing, Discord Bots. I'm mostly known as "root". Add me as a friend there and we'll talk about it!
